### ISSUE TITLE
Some clarifications on the datasets

### ISSUE THREAD

**Issue by weihua916** [yangkevin2/coronavirus_data#4]
Thank you for the amazing effort! I am excited to try out your datasets and contribute to COVID-19 research.

I would like to get some clarifications on the datasets and the splits that you would like us to use for evaluation. I initially thought they are in https://github.com/yangkevin2/coronavirus_data/blob/master/splits.zip, but you also used https://github.com/yangkevin2/coronavirus_data/blob/master/old/AID1706_splits.zip for 5-fold CV, scaffold splits.
Which one do you expect us to use, and which one did you use when you obtain E.coli 0.887 and SARS-CoV-3CLpro 0.722 in https://www.aicures.mit.edu/tasks? Also, what is the relationship between these two datasets and the main dataset on pseudonomas aeruginosa? Finally, are SARS-CoV-3CLpro and AID1706 the same dataset or are they different ones? I initially thought they are the same but saw a section called "Multi-task training for SARS-COV-2 3CLPro and AID1706" and got a bit confused.

Thanks in advance.

**Comment by swansonk14** [comment]
Thank you! I'm glad you're interested in contributing!

The splits to use are in [splits.zip](https://github.com/yangkevin2/coronavirus_data/blob/master/splits.zip). The [AID1706_splits.zip](https://github.com/yangkevin2/coronavirus_data/blob/master/old/AID1706_splits.zip) is a 5-fold CV split we were using before, but we decided that it would be easier for people to work with just a single train/dev/test split. When evaluating your own models, it would still be a good idea to use cross-validation to get a more robust estimate of model performance, but we're going to be reporting numbers on the train/dev/test splits in [splits.zip](https://github.com/yangkevin2/coronavirus_data/blob/master/splits.zip).

Sorry for the confusion about the multi-tasking section! I actually just removed that section to avoid confusion and since it's not fully up to date. But to explain what we were trying, we were experimenting with training on both [AID1706_binarized_sars.csv](https://github.com/yangkevin2/coronavirus_data/blob/master/data/AID1706_binarized_sars.csv), which is data on the 3CLpro target for SARS-CoV (the virus that caused SARS in 2002/3), and on [mpro_xchem.csv](https://github.com/yangkevin2/coronavirus_data/blob/master/data/mpro_xchem.csv), which is data on the 3CLpro target for SARS-CoV-2 (the virus that causes COVID-19). Since there's so little data on SARS-CoV-2, we were hoping that multi-task training with data for SARS-CoV might help boost performance on SARS-CoV-2, and we did see some of that effect. We're still experimenting with this. (I think the confusion was that AID1706 is data for SARS-CoV, which is different from SARS-CoV-2.)

**Comment by swansonk14** [comment]
Actually I'm going to add the multi-tasking section back to the readme but with a description that will hopefully clear up any confusion.

Please let us know if you have any other questions!

**Comment by weihua916** [comment]
Thank you for the clarification! They are really helpful.

Just want to follow up two questions that I would like a further clarification.
1. Are the E.coli 0.887 and SARS-CoV-3CLpro 0.722 in the [webpage](https://www.aicures.mit.edu/tasks) evaluated on the [splits.zip](https://github.com/yangkevin2/coronavirus_data/blob/master/splits.zip)?
2. Is SARS-CoV-2 data in [mpro_xchem.csv](https://github.com/yangkevin2/coronavirus_data/blob/master/data/mpro_xchem.csv) the same as the [open task](https://www.aicures.mit.edu/data)?  There seems to be fewer molecules in  [mpro_xchem.csv](https://github.com/yangkevin2/coronavirus_data/blob/master/data/mpro_xchem.csv) than 2,366 in the open task.

Thanks!

**Comment by swansonk14** [comment]
I'm glad I could help!

Here are answers to your other two questions:

1. Yes the numbers on the website are evaluate on the [splits.zip](https://github.com/yangkevin2/coronavirus_data/blob/master/splits.zip).
2. No the SARS-CoV-2 data in [mpro_xchem.csv](https://github.com/yangkevin2/coronavirus_data/blob/master/data/mpro_xchem.csv) is different from the open task. The open task is data on [pseudomonas aeruginosa](https://en.wikipedia.org/wiki/Pseudomonas_aeruginosa), which can cause secondary bacterial pneumonia in COVID-19 patients. We're still finalizing the dataset (I think it'll be ready tonight) but it will actually have 2,335 molecules. This is the exact same set of molecules as the E. coli data but with new activity values for pseudomonas.
