### ISSUE TITLE
Error Building SciPy

### ISSUE THREAD

**Issue by daverdude** [yangkevin2/coronavirus_data#7]
I have been using chemprop since early last year and recently had to rebuild the program, but I have continuously been met with an error while building the wheels for SciPy (Error with PEP 517). Not sure if the dependencies listed in the requirements txt file are outdated, but I have not been able to solve this issue.

**Comment by yangkevin2** [comment]
Did you mean to post this issue to the chemprop repo https://github.com/chemprop/chemprop?

Anyway, if you still have your old installation, maybe you could run pip freeze on the old version and check your package versions compared to your new installation; maybe an update to one of the required packages broke something? You could also try going back to an older commit of chemprop to see if the issue is with chemprop itself, but the former problem seems more likely to me from your description.

**Comment by daverdude** [comment]
Yeah, I definitely meant to put this on the actual chemprop hub! I think python 3.9 might have broken the installation, so I’ll downgrade to 3.7 or 3.8 to see if that helps! Thanks for the reply!
